version: "4.23"
services:
  app:
    build:
      context: .
    volumes:
      - .:/untitled3
    ports:
      - "3000:3000"
    image: app:react
    container_name: react_container
    command: npm start
